# Generated by Django 4.1.7 on 2023-05-07 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0005_remove_commande_produits_delete_produitnc_and_more'),
        ('magasin', '0007_commande'),
    ]

    operations = [
    ]
