# Generated by Django 4.1.7 on 2023-05-08 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0009_produitnc_remove_produit_categorie_and_more'),
    ]

    operations = [
    ]
