# Generated by Django 3.0.5 on 2023-05-12 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0011_auto_20230512_2119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
