# Generated by Django 3.0.5 on 2023-05-12 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0013_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
