# Generated by Django 3.0.5 on 2023-05-12 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0014_delete_contact'),
    ]

    operations = [
    ]
