# Generated by Django 3.0.5 on 2023-05-12 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0016_delete_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContenuPanier',
        ),
        migrations.DeleteModel(
            name='Panier',
        ),
    ]
