# Generated by Django 3.0.5 on 2023-05-12 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0017_auto_20230512_2349'),
    ]

    operations = [
    ]
