# Generated by Django 3.0.5 on 2023-05-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0018_delete_magasin_panier_table'),
    ]

    operations = [
    ]
